### PR TITLE
Backend for custom game profiles #2

### PR DESCRIPTION
**Pull request by maniman303**
Here is the backend solution for dealing with custom refresh rate and fps limit per game.

The idea is to store profiles per game in json files, then run a timer function per every x seconds which will get the name of the exe of the currently running game. If there is a game and there is a profile with settings for it - use it. Otherwise use default profile.

At start PowerControls.exe will make a new folder at ./Profiles if such doesn't exists. Then it will create a Default.json file containing saved settings for default profile. Because of this as a bonus we get saved configs for "desktop mode".

For now it only supports fps and refresh rate settings, but it should be easily expandable for other settings.

### CODE REVIEW

**Comment by navarayuk** [comment]
Polling all the time isn't a good thing maybe you could have a command line what could create a shortcut for the game what includes the path ofthe game and when the game is started it also starts the profile for the game, windows and polling ever few seconds, the idea is pretty good but removing the need to poll it ever few seconds isn't a good idea unless it only does it when you first change the game mode pad but how will it deal with more then one game, I at times have had 3 games open how would it handle this ?

**Comment by maniman303** [comment]
Right now I have to implement a few changes to correctly support multi display, but the overall idea is like this:

If there's more then one display profiles will be disabled entirely.

Then if no games are running default profile is being used. If there's only one game running and there's a profile for it - a profile for the game is being used. In every other case (eg. multiple games are running) default profile is being utilized.

The thing I'm focusing on here is simplicity and the best possible experience for average user. And deck is used by average user to play one game at the time. Also command line and stuff like that add too much complexity, shortcuts can break easily when launcher like steam is involved and overall experience is far from "set up and forget".

Probably a more mature implementation would listen to some system events when exes are being opened / closed. I will take a look at this, but we already are polling constantly, so "what's one more" (kidding ofc).

**Comment by maniman303** [comment]
@ayufan I was thinking about making profile values changes a bit more simple. Right now if there is an update to the profile info about it is passed from profile controller to controller class, then controller for each change calls root menu. But what if we remove controller from the equation? If we would make profile controller observable each menu item with a key could listen for changes in profile and react accordingly. This way controller is not used for handling changes, and no sensitive methods are exposed to be public

**Comment by ayufan** [comment]
@maniman303 I do not yet have good design for this. I need to sit to it to figure out what would fit the best. I think I agree with overall perspective. It would be best if Options could be observable, as then a change could be cleanly persisted.

**Comment by maniman303** [comment]
Ok, thing about it and let me know if observable idea might work. If it will be I will start coding it in the near future. Meanwhile I've added support for multi displays and a better way of handling games that mess with refresh rates etc.

**Pull request closed without merging**
